create database movie;
use movie;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE Review (
  ReviewID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  MovieID INT  NOT NULL,
  TextReview TEXT,
  FOREIGN KEY (UserID) REFERENCES Users (UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies (MovieID)
);
CREATE TABLE Movies (
  MovieID INT AUTO_INCREMENT PRIMARY KEY,
  PathImage VARCHAR(255) NOT NULL UNIQUE,
  Name VARCHAR(255) NOT NULL,
  Description TEXT
);
CREATE TABLE GradeMovie (
  GradeID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  MovieID INT  NOT NULL,
  Grade INT(10),
  FOREIGN KEY (UserID) REFERENCES Users (UserID),
  FOREIGN KEY (MovieID) REFERENCES Movies (MovieID)
);

CREATE TABLE Collections (
  CollectionID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(255) NOT NULL UNIQUE,
  FOREIGN KEY (UserID) REFERENCES Users (UserID)
);

CREATE TABLE CollectionsMovie (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CollectionID INT NOT NULL,
  MovieID INT NOT NULL,
  FOREIGN KEY (MovieID) REFERENCES Movies (MovieID),
  UNIQUE (CollectionID, MovieID)
);